package com.example.simpleweatherapp.data.offline

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a City entity in the database.
 *
 * This class defines the schema for the `cities` table in the database.
 * Each instance of this class corresponds to a row in the table.
 *
 * @param id The unique identifier for the city, serving as the primary key.
 *           It is auto-generated by the database.
 * @param name The name of the city.
 */
@Entity(tableName = "cities")
data class City(
    /**
     * The unique identifier for each city entry.
     * This value is auto-generated when a new city is added to the database.
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    /**
     * The name of the city.
     */
    val name: String
)
